import 'logik.dart';

const wasHeuteTun = [
  "TABS Turnier (als nächstes Liga 1)",
  "Programmiersprache lernen",
  "PES Spieler erstellen",
  "random wiki seite durchlesen",
  "Boxer Name suchen (Boxrec)",
  "10 ayas lesen (+ Qurangarden eine Folge anhören)",
  "lernen",
  "sprache Lernen",
  "Lesen",
  "brilliant.org/Khan academy Kurs",
  "Instrument lernen (flowkey)",
  "GD level üben",
  "Schach lernen",
  "rainmeter skin",
  "sport",
  "tutoriel"
];
const youtube = [
  "Lofi",
  "YouTubeVideo",
  "Epic",
  "Music Mix (irgendeiner)",
  "Mein Mix (auf youtube)",
  "EDM",
  "Dubstep",
  "homepage: erstes Musikdings",
  "youtube music (mein Supermix)",
  "box.com",
  "youtube music andere Sache",
  "was ich will",
  "discord",
  "zufällige Playlist meinerseits",
  "koran",
  "podcast",
  "telefonieren",
  "nichts",
  "Japanese",
  "tutoriel"
];
var library = [
  Playlist("My Likes", "Dubstep Epic EDM Japanese Lofi",
      "https://music.youtube.com/playlist?list=LM"),
  Playlist(
      "yt mix von der Art",
      [genres.Dubstep, genres.EDM, genres.Epic, genres.Japanese, genres.Lofi],
      "music.youtube.com"),
  Playlist(
      "auf yt music suchen",
      [genres.Dubstep, genres.EDM, genres.Epic, genres.Japanese, genres.Lofi],
      "music.youtube.com"),
  Playlist("auf youtube suchen", "EDM Dubstep Epic Japanese Lofi", "youtube"),
  Playlist("2010", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCbu-NBkoYAoLiM9rlqx1mym"),
  Playlist("latest recap", "EDM Dubstep",
      "https://music.youtube.com/playlist?list=LRSRYqFgw0T2e1gzYxh5yZSw_9VhojXnRLE2A"),
  Playlist("Absolut geilste Lieder", "Dubstep Japanese EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZVrGqaEne-YncoF460oTwZ&feature=share"),
  Playlist("Absolut heftigste Drops", "Dubstep",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCYmE8KRapaFp0DazXSslprx&feature=share"),
  Playlist("All time GOATs", "Dubstep",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCYcJpxKhgsEy7YnH1JSndaB&feature=share"),
  Playlist("AMV Material", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZbM-iAkKkBxU7L1X5LunyU&feature=share"),
  Playlist("Anime openings", "Japanese",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCbmzuhf8h0hno8Tenl7q_t6&feature=share"),
  Playlist("ANIMEEEE", "Japanese",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCYZ2AbhJTLG9gLCq288S3Wj&feature=share"),
  Playlist("Chill Japanese uwu", "Japanese",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCbKoCeLzsq6ZziyEvD8VmZ2&feature=share"),
  Playlist("Chillig", "Lofi",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCaaaf1Jo-DZ5DdpmibvntTH&feature=share"),
  Playlist("Copyright Free", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCan9HBxMwe3enKMb5xkEPg7&feature=share"),
  Playlist("Cybersongs", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCYmPaDA-5MwL_2-r6U3iGLB&feature=share"),
  Playlist("Dubstep", "Dubstep",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCY-zQ-hkmxSfC0bAkZYHT7Q&feature=share"),
  Playlist("E-guitar or something", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCaolgZ-OB4ZMm-WQzkGxg5d&feature=share"),
  Playlist("Epic beatbox shttt", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCbcffjwrOt5Yq1pByf4h1Bl&feature=share"),
  Playlist("Epic mewsik", "Epic",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCax8aO9ZCYw2wMfPuMGizEy&feature=share"),
  Playlist("Flöte", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCYHShf5fcaWbjUlmsJbdhns&feature=share"),
  Playlist("Geile Drops", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCYRm9Gc1hfqsrBtBT_P7syy&feature=share"),
  Playlist("Geile Lieder", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCarQULF4uBtg5YyoemN2yet&feature=share"),
  Playlist("Good ol times", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCb1bFxrAuSoG8WIspsp2qRV&feature=share"),
  Playlist("Good old music", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCbjbBGA1J3db0qUF5jPajL7&feature=share"),
  Playlist("Handstand", "Dubstep",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZUIpUQMmBG8brp_NELv8Yu&feature=share"),
  Playlist("Insta story", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCb_DHKN_gKTZD1bMHVP4_oi&feature=share"),
  Playlist("K-Hollow Clop Snare", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCbtLP4PXa7WX-uh7wYm0JbW&feature=share"),
  Playlist("Kewl Lofi", "Lofi",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCaAGrpAl6iIKnXbKEDJgyp9&feature=share"),
  Playlist("Mizwed", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZYX-jT79fRLqB_4e2amJVY&feature=share"),
  Playlist("Montage Material", "Dubstep EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZs4kzJ_8N4yRQ7gg1RRTJz&feature=share"),
  Playlist("My mix made by me lol", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZ158UdBAhFGmCKnJV_GRA-&feature=share"),
  Playlist("OSTs", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCaENfyOIYKIvWhN3px4lFk5&feature=share"),
  Playlist("Programming", "Lofi",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCb9f_pnzHECIT2WaYQIKLyN&feature=share"),
  Playlist("Rep beats", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCaOZ4IRJNR-UKyygP4laYHC&feature=share"),
  Playlist("Running", "Dubstep EDM Epic",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZqAIZtZBiiCVeU4zpEwrX2&feature=share"),
  Playlist("Stargazing", "Lofi",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCadcKh2JmiyV8rOXiQJtkwy&feature=share"),
  Playlist("Toaster", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCa23m6Te9FZYxOKF8AL_Xpf&feature=share"),
  Playlist("Trompete", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCYMPSzuiAnF-0rXkYZFtqTe&feature=share"),
  Playlist("Tunisia", "",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCZMcIXDNY_Mqvx5I6CCFqj1&feature=share"),
  Playlist("Workout", "EDM",
      "https://music.youtube.com/playlist?list=PLEZw-N-2kUCalikUCuev7cHUKxJG5JVaH&feature=share") //EDM, Dubstep, Epic, Japanese, Lofi
];
const podcasts = [
  "Joe Rogan",
  "StarTalk Radio",
  "THE FIGHT with Teddy Atlas",
  "ColdFusion",
  "The Colin & Samir Show",
  "Hotboxin with Mike Tyson",
  "DIESDAS",
  "Clixoom - Science & Future",
  "Trash Taste Podcast",
  "Waveform: The MKBHD Podcast",
  "Quran Garden",
  "neuer Podcast"
];
const tutoriel = ["blender", "Dart/Flutter", "Gimp", "Shotcut"];

const box_com = [
  "maybe illegal anime streaming",
  "Crunchyroll",
  "Netflix",
  "Disney+",
  "Prime Video",
  "Ps4 zocken",
  "Youtube music",
  "Switch",
  "Generell Gaming",
  "Wakanim",
  "Youtube",
  "Joyn",
  "Was ich will",
  "Pc zocken",
  "Prosiebenmaxx",
  "Twitch",
  "TvNow",
  "Myanimelist Anime",
  "ultimate legal anime list Dings",
  "Netzkino",
  "anime2you",
  "Anime den ich gerade aktiv schaue",
  "Komplett random anime auf Kitsu",
  "nichts",
  "Fernseher",
  "Highest rated anime on Kitsu I haven't watched yet",
  "Pokémon Tv",
  "Game I'm actively playing right now",
  "Discord",
  "Plutotv",
  "Amazon Freevee",
  "Apple TV",
  "Sports",
  "Tv time recommendation",
  "Tv time Liste",
  "Manga/Buch",
  "iqiyi",
  "Aldi Musik"
];

enum genres { EDM, Dubstep, Epic, Japanese, Lofi }
