// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkMnwGydllx-LwmeTenHVto7QhonvNyyg',
    appId: '1:812883282747:web:0d0ec7239c7c064be3851e',
    messagingSenderId: '812883282747',
    projectId: 'testowomegaapp',
    authDomain: 'testowomegaapp.firebaseapp.com',
    storageBucket: 'testowomegaapp.appspot.com',
    measurementId: 'G-QSP6N33LNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ1qznJ0Ml6XSHsbEFVOzcEMXLfE4woUY',
    appId: '1:812883282747:android:cd68588f917dd68ae3851e',
    messagingSenderId: '812883282747',
    projectId: 'testowomegaapp',
    storageBucket: 'testowomegaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Lb8tL3DIdKrts96yf1-XFcwCCMeRHzc',
    appId: '1:812883282747:ios:cd90a6bf4db7a45ce3851e',
    messagingSenderId: '812883282747',
    projectId: 'testowomegaapp',
    storageBucket: 'testowomegaapp.appspot.com',
    iosClientId: '812883282747-dnenquldrqv862s7gds0a0sfh80piui4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testOwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Lb8tL3DIdKrts96yf1-XFcwCCMeRHzc',
    appId: '1:812883282747:ios:b89c37cf0fb1adb8e3851e',
    messagingSenderId: '812883282747',
    projectId: 'testowomegaapp',
    storageBucket: 'testowomegaapp.appspot.com',
    iosClientId: '812883282747-q64kc44399qbsd1prba2eqtlg2mbkml8.apps.googleusercontent.com',
    iosBundleId: 'rolf.kopter',
  );
}
